version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["security", "dependencies"]
    security-updates:
      automerge: true
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels: ["security", "dependencies"]
    security-updates:
      automerge: true
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "ci"]
